#!/bin/bash
set -e

MYSQL="mysql -u${MYSQL_USER_ROOT}"

echo "Creating database: ${MYSQL_DATABASE}"

$MYSQL <<EOSQL
CREATE DATABASE ${MYSQL_DATABASE};
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO ${MYSQL_USER}@%;
FLUSH PRIVILEGES;
EOSQL


